org: photonadmin
app: photonranch

service: ptrdata

provider:
  name: aws
  runtime: python3.7
  environment: 
    WSS_URL:
      Fn::Join:
        - ""
        - - "https://"
          - Ref: "WebsocketsApi"
          - ".execute-api.us-east-1.amazonaws.com/dev"

  iamRoleStatements:
    - Effect: "Allow"
      Action:
          - "s3:GetBucketNotification"
          - "s3:PutBucketNotification"
      Resource:
        Fn::Join:
          - ""
          - - "arn:aws:s3:::photonranch-001 or *"
    - Effect: Allow 
      Action: 
        - "execute-api:ManageConnections"
      Resource:
        - "arn:aws:execute-api:*:*:**/@connections/*"

    - Effect: Allow 
      Action: 
        - "dynamodb:PutItem"
        - "dynamodb:GetItem"
        - "dynamodb:UpdateItem"
        - "dynamodb:DeleteItem"
        - "dynamodb:BatchGetItem"
        - "dynamodb:BatchWriteItem"
        - "dynamodb:Scan"
        - "dynamodb:Query"
        - dynamodb:DescribeStream
        - dynamodb:GetRecords
        - dynamodb:GetShardIterator
        - dynamodb:ListStreams
      Resource:
        - "arn:aws:dynamodb:us-east-1:*:*"

functions:
  insert_data:
    handler: insert_data.main
    events:
      - existingS3:
          bucket: photonranch-001
          events: 
          - s3:ObjectCreated:* 
  connectionManager:
    handler: handler.connection_manager
    events:
      - websocket:
          route: $connect
      - websocket:
          route: $disconnect
  defaultMessage:
    handler: handler.default_message
    events:
      - websocket:
          route: $default

plugins:
  - serverless-dotenv-plugin
  - serverless-plugin-existing-s3
  - serverless-python-requirements

package:
  exclude:
    - venv/**
    - .env
    - lambda_tests.txt

resources:
  Resources:

    # This table tracks websocket clients that recieve data updates.
    dataSubscribers: 
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: photonranch-data-subscribers1
        AttributeDefinitions:
          - AttributeName: ConnectionID
            AttributeType: S
          #- AttributeName: Observatory
            #AttributeType: S
        KeySchema:
          - AttributeName: ConnectionID
            KeyType: HASH
          #- AttributeName: Observatory
            #KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1